repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: ["--line-length=119"]
        exclude: '^lesson_scheduler_api/core/migrations/'

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          - pyproject-flake8
          - flake8-bugbear
          - flake8-assertive