FROM python:3.10

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  # pip:
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # poetry:
  POETRY_VERSION=1.7.1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry'

# System deps:
RUN apt update
RUN apt-get install libicu-dev
RUN pip install "poetry==$POETRY_VERSION" && poetry --version

# Set working directory
WORKDIR /app
COPY pyproject.toml poetry.lock /app/

# Install dependencies
RUN poetry config virtualenvs.create false
RUN poetry install $(test "$VAI_ENV" == production && echo "--no-dev") --no-interaction --no-ansi --no-root

# Copy project
COPY . .

WORKDIR /app/lesson_scheduler_api
ENTRYPOINT pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m celery -A dashboard worker --loglevel=INFO --pool=solo