# Generated by Django 3.2.18 on 2023-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('number_booked', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
