# Generated by Django 3.2.24 on 2024-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240608_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='missed_booking',
            field=models.IntegerField(default=0),
        ),
    ]
