# Generated by Django 3.2.24 on 2024-06-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_missed_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
