# Generated by Django 3.2.24 on 2024-06-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='missed_booking',
            new_name='missed_bookings',
        ),
    ]
