# Generated by Django 3.2.24 on 2024-06-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_missed_booking_user_missed_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expired_booking',
            field=models.BooleanField(default=False),
        ),
    ]
